### PR TITLE
Hex plots

### PR DESCRIPTION
**Pull request by seaaan**
Did you think about using `geom_hex()` for plots? I've been getting annoyed waiting for plots to load when I have a full plate of data (either using `ddpcr::plot()` or anything else with `geom_point()`). Using `geom_hex()` seems to be a quicker alternative and still gives a lot of information. 

Here is an example of how it could be work. I wouldn't mean for this pull request to actually get accepted, but instead to be an example. (I don't understand the details of how all the options to `ddpcr::plot()` get used and the various situations where you'd use them, so it might break in some cases.) I know a rainbow-esque color scale is not ideal, but I'm so used to flow cytometry data that it's much more informative to me than just a single color scale.  

I would be interested in any suggestions or criticisms.

### CODE REVIEW

**Comment by daattali** [comment]
I will reply hopefully within a week, I have family visiting and lots of meetings and finding myself a bit swamped :)  Thanks for contributing so much!

**Comment by seaaan** [comment]
No rush at all. It's been a little slow at work lately is all, so I'm
trying to get the infrastructure in place for future analysis of our
triplex ddPCR assays, which is why these pull requests have come at once.
But nothing is a rush from my perspective.

**Comment by daattali** [comment]
You really went to town trying to understand the entire code in this huge plotting function! That's never an easy task, to dive into a 200-line function that someone else wrote..... I feel so exposed having someone see so much of my code so up close!

The only thing about these hex plots is that they only convey density but cannot convey different sections of drops. Is it very useful to you to just show a simple density of all the droplets?

**Comment by seaaan** [comment]
By different sections of drops, do you mean clusters? I.e. FAM+HEX-, FAM+HEX+, FAM-HEX+? 

I guess the density is useful to me because my analysis mainly involves setting complicated thresholds, so looking at the droplet distribution in relation to the thresholds/gates helps me determine whether the thresholds are appropriate. Here is an [example](https://github.com/daattali/ddpcr/files/407320/example.pdf). The thresholds here are pretty good for G02 and H02, but not for F02 or F03 and, in addition, there's something weird in the negative population in F03. With repeated changing of the thresholds to find the appropriate one for an experiment, the hex plots are nice because they render much more quickly. 

Don't feel too exposed: for what it's worth, your package has mostly been very easy for me to extend and modify, it's really nice. Especially adding my own plate type to do gating/complex thresholds like this was relatively easy to figure out and is so much better than QuantaSoft! Our strategy up until now had been an insane system of repeatedly adjusting the thresholds in QuantaSoft and outputting files and then combining those files and adding/subtracting as appropriate to get the regions we want.

**Comment by daattali** [comment]
Got it. So would this option only support visualizing all the drops as one
category (/cluster), in the sense that the only information it will convey
is the density of the droplets but nothing else?  If this seems to make
sense to you, then what do you think of having an argument in the plot
function "quick = TRUE/FALSE" and it's FALSE by default but if it's true
then a lot of the parameters are ignored and it just does this quick plot?

---
http://deanattali.com

**Comment by daattali** [comment]
Cool I can get on board that :) I don't have much time to dedicate to this
package in the coming weeks I'll do it later if yiu ipen an issue, or I'll
accept a PR!

**Comment by seaaan** [comment]
Okay, I'll do it sometime in the next couple of weeks.

**Comment by daattali** [comment]
Closing this due to 2+ years of inactivity

**Pull request closed without merging**
